[project]
name = "controlling-servo-motors"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adafruit-circuitpython-servokit>=1.3.22",
    "uv>=0.9.5",
]
